FROM ctuning/ck-milepost-gcc-ubuntu16.04
MAINTAINER David Greasley <david.greasley.2017@my.bristol.ac.uk>

RUN apt-get update

RUN apt-get install -y vim
RUN apt-get install -y gfortran


RUN git config --global user.email "davidgreasley@btopenworld.com"
RUN git config --global user.name "David Greasley"

