#!/bin/bash

#SBATCH --job-name measure-sleep
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 28
#SBATCH --time 0:10:00
#SBATCH --partition cpu_test
#SBATCH --output sleep.out
#SBATCH --exclusive

export OMP_NUM_THREADS=27

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

~/masters-project/energy-monitor/energy-monitor sleep 95
